service: issue-service

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1

plugins:
  - serverless-auto-swagger
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

functions:
  issueHandler:
    handler: handler.handler
    events:
      - http:
          path: issues
          method: get
      - http:
          path: issues
          method: post
      - http:
          path: issues/{id}
          method: get
      - http:
          path: issues/{id}
          method: patch
      - http:
          path: issues/{id}/assign
          method: patch
      - http:
          path: issues/{id}/resolve
          method: patch
      - http:
          path: issues/{id}/reopen
          method: patch
